INSERT INTO Questions
VALUES
(1,'MCQ','Which of the following methods can not be used to enter data in a cell?','Pressing the Esc key',101),
(2,'MCQ','Which of the following will not cut information?','Pressing Ctrl + C',101),
(3,'MCQ','Which of the following is not a way to complete a cell entry?','Pressing spacebar',101),
(4,'MCQ','You can activate a cell by','All of the above',101),
(5,'MCQ','Text formulas:','Concatenate and manipulate text',101),
(6,'MCQ','How do you insert a row?','Right-click the row heading where you want to insert the new row and select Insert from the shortcut menu',101),
(7,'MCQ','Which of the following is not a basic step in creating a worksheet?','Copy the worksheet',101),
(8,'MCQ','How do you select an entire column?','Click the column heading letter',101),
(9,'MCQ','How can you print three copies of a workbook?','Select File >Print from the menu and type 3 in the Number of copies text box.',101),
(10,'MCQ','To create a formula you first:','Select the cell you want to place the formula into',101),
(11,'MCQ','To center worksheet titles across a range of cells you must','Select the cells containing the title text plus the range over which the title text is to be centered',101),
(12,'MCQ','How do you delete a column?','Right click the column heading you want to delet and select delete from the shortcut menu',101),
(13,'MCQ','How can you find specific information in a list?','Select Data > Form from the menu to open the Data Form dialog box and click the Criteria button',101),
(14,'MCQ','When integrating word and excel word is usually the','Both b and c',101),
(15,'MCQ','When a label is too long to fit within a worksheet cell you typically must','Increase the column width',101),
(16,'MCQ','The name box','Appears to the left of the formula bar',101),
(17,'MCQ','Comments put in cells are called','Cell tip',101),
(18,'MCQ','Which is used to perform what if analysis?','All of above',101),
(19,'MCQ','You can use the horizontal and vertical scroll bars to','View different rows and columns edit the contents of a cell',101),
(20,'MCQ','Multiple calculations can be made in a single formula using','array formula',101),
(21,'TF','If you do not save your workbook you can recover any lost data the next time you start Excel.','False',101),
(22,'TF','After you click the Save toolbar button the Save dialog box will appear if the file already exists.','False',101),
(23,'TF','Excel will not regard the entry as text if any numbers are included with text in the entry.','False',101),
(24,'TF','Instead of typing in cell references you can use the mouse click for Excel to enter the cell names into formulas for you.','True',101),
(25,'TF','You can only select cells that are adjacent to each other.','False',101),
(26,'TF','Dragging the mouse or holding the down the Shift key while clicking with the mouse will only select cells that are adjacent to each other.','True',101),
(27,'TF','If you want to move large amounts of data within a worksheet or from one worksheet to another its better to use the cut and paste method..','True',101),
(28,'TF','You can paste the copied data to more than one selected cell or range.','True',101),
(29,'TF','You can only insert one column row or cell at a time.','False',101),
(30,'TF','Rows and Columns can be inserted by selecting the Cells command from the Insert menu.','True',101),
(31,'MCQ','Contains reference data such as descriptive attributes__________________','Dimension table',104),
(32,'MCQ','What is the recommend method to share your reports?','Publish them to the Power BI service',104),
(33,'MCQ','What symbol would you use for multiplication in Power BI in a DAX formula?','*',104),
(34,'MCQ','Berikut contoh fungsi COUNTING kecuali________________','MAX',104),
(35,'MCQ',' Type of data modeling in Power BI that Uses Data Analysis Expressions and similar to Excel formulas______________','DAX',104),
(36,'MCQ','Berikut contoh LOGICAL Functions di DAX kecuali____________','SUMX',104),
(37,'MCQ','Fungsi yang termasuk di kategori TEXT FUNCTION_______________','CONCATENATE',104),
(38,'MCQ','Sometimes referred to as Power BI online______________','Power BI Service',104),
(39,'MCQ','Creates the connection between Power BI cloud-based data and the data source located on-premises_______________','Gateway',104),
(40,'MCQ','Calculate a result from an expression formula and the result can only be viewed in the visualization______________','Measures',104),
(41,'MCQ',' A customer may purchase 1 or many products. So the relationship between the customer table and the products table will be_________________','One to Many',104),
(42,'MCQ','The topic of discussion of Power BI Session 4 is_______________','Introduction to DAX',104),
(43,'MCQ','A function that can only work on numeric fields is_______________','AVERAGE',104),
(44,'MCQ','Which is used to calculate the data in each row__________________','Calculated Colum',104),
(45,'MCQ','Contains transactional data or facts of a business process_______________','Fact table',104),
(46,'MCQ','Which of these values would be matched using the syntax LIKE “%apple”','All of mentioned above',104),
(47,'MCQ','What are the group of data sources can Power BI connect to' ,'Files- Content Packs- Connectors',104),
(48,'MCQ','What DAX function can be used to return a value in a column if a condition is met?','IF',104),
(49,'MCQ','Which of the following are building blocks of Power BI?','Visualizations- datasets- reports- dashboards- tiles',104),
(50,'MCQ','A collection of data that you import or connect to___________','Datasets',104),
(51,'TF','When composing the DAX articulation for a measure you can accept your DAX code consequently has push setting for the table in which the measure is characterized
','False',104),
(52,'TF','When composing the DAX articulation for a figured segment you can expect your DAX code naturally has push setting for the table in which the ascertained segment is characterized.','False',104),
(53,'TF','If you want the data to automatically refresh as you interact with visualisations should you choose Import option?','False',104),
(54,'TF','You need a Power BI Pro license to share your dashboard but those you share it with do not need a license. When you share a dashboard they can view it and interact with it but cant edit it. They see the same data that you see in the dashboard and reports unless row-level security (RLS) is applied to the underlying dataset. The colleagues you share it with can share the dashboard with their colleagues if you allow them to.','False',104),
(55,'TF','An individual step can be removed in Power Query Editor.','True',104),
(56,'TF','You have a user named User1. User1 is a member of a security group named Contoso PowerBI.User1 has access to a workspace named Contoso Workspace.You need to prevent User1 from exporting data from the visualizations in Contoso Workspace.
Solution: From the PowerBI setting you modify the Developer Settings.
Does this meet the goal?','False',104),
(57,'TF','Filters on this visual" will apply a filter to all of your charts.','False',104),
(58,'TF','Financial and date/time are examples of hierarchical data that would suit a drill-down well?','False',104),
(59,'TF','Tooltips appear when the user hovers over part of a visual (e.g. pie segment) even when there are no fields in the Tooltip data bucket.','True',104),
(60,'TF','A CSV preview allows choosing a delimiter.','True',104),
(61,'MCQ','What is a correct syntax to output "Hello World" in C#?','Console.WriteLine("Hello World") ;',102),
(62,'TF','C# is an alias of C++','False',102),
(63,'MCQ','How do you insert COMMENTS in C# code?','// This is a comment',102),
(64,'MCQ','Which data type is used to create a variable that should store text?','string',102), 
(65,'MCQ','How do you create a variable with the numeric value 5?','int x = 5;',102), 
(66,'MCQ','How do you create a variable with the floating number 2.8?','double x = 2.8D;',102),
(67,'MCQ','How do you create a variable with the floating number 2.8?','Length',102),
(68,'MCQ','Which operator is used to add together two values?','The + sign',102),
(69,'TF','The value of a string variable can be surrounded by single quotes','False',102),
(70,'TF','Type casting is when you assign a value of one data type to another type','True',102),
(71,'MCQ','Which operator can be used to compare two values?','==',102),
(72,'MCQ','To declare an array in C# define the variable type with','[]',102),
(73,'MCQ','Array indexes start with','0',102),
(74,'MCQ','How do you create a method in C#','MyMethod()',102),
(75,'MCQ','How do you call a method in C#','MyMethod();',102),
(76,'MCQ','Which keyword is used to create a class in C#','class',102),
(77,'MCQ','What is the correct way to create an object called myObj of MyClass','MyClass myObj = new MyClass();',102),
(78,'TF','In C# it is possible to inherit fields and methods from one class to another','True',102),
(79,'MCQ','What is the name of the "special" class that represents a group of constants','enum',102),
(80,'MCQ','Which operator is used to multiply numbers','*',102),
(81,'MCQ','Which access modifier makes the code only accessible within the same class','private',102),
(82,'MCQ','How do you start writing an if statement in C#','if (x > y)',102),
(83,'MCQ','How do you start writing a while loop in C#','while (x > y)',102),
(84,'MCQ','Which keyword is used to return a value inside a method','return',102),
(85,'MCQ','Which statement is used to stop a loop?','break',102),
(86,'MCQ','What does SQL stand for','Structured Query Language',103),
(87,'MCQ','Which SQL statement is used to extract data from a database','SELECT',103),
(88,'MCQ','Which SQL statement is used to update data in a database','UPDATE ',103),
(89,'MCQ','Which SQL statement is used to delete data from a database','DELETE',103),
(90,'MCQ','Which SQL statement is used to insert new data in a database','INSERT INTO ',103),
(91,'MCQ','With SQL how do you select a column named "FirstName" from a table named "Persons"','SELECT FirstName FROM Persons ',103),
(92,'MCQ','With SQL how do you select all the columns from a table named "Persons"','SELECT * FROM Persons',103),
(93,'MCQ','With SQL how do you select all the records from a table named "Persons" where the value of the column "FirstName" is "Peter"','SELECT * FROM Persons WHERE FirstName="Peter"',103),
(94,'MCQ','With SQL how do you select all the records from a table named "Persons" where the value of the column "FirstName" starts with an "a"','SELECT * FROM Persons WHERE FirstName LIKE "a%" ',103),
(95,'TF','The OR operator displays a record if ANY conditions listed are true. The AND operator displays a record if ALL of the conditions listed are true','True',103),
(96,'MCQ','With SQL how do you select all the records from a table named "Persons" where the "FirstName" is "Peter" and the "LastName" is "Jackson"','SELECT * FROM Persons WHERE FirstName="Peter" AND LastName="Jackson"',103),
(97,'MCQ','With SQL how do you select all the records from a table named "Persons" where the "LastName" is alphabetically between (and including) "Hansen" and "Pettersen"','SELECT * FROM Persons WHERE LastName BETWEEN "Hansen" AND "Pettersen"',103),
(98,'MCQ','Which SQL statement is used to return only different values','SELECT DISTINCT',103),
(99,'MCQ','Which SQL keyword is used to sort the result-set','ORDER BY ',103),
(100,'MCQ','With SQL how can you return all the records from a table named "Persons" sorted descending by "FirstName"','SELECT * FROM Persons ORDER BY FirstName DESC',103),
(101,'MCQ','With SQL how can you insert a new record into the "Persons" table','INSERT INTO Persons VALUES ("Jimmy" "Jackson")  ',103),
(102,'MCQ','With SQL how can you insert "Olsen" as the "LastName" in the "Persons" table','INSERT INTO Persons (LastName) VALUES ("Olsen")',103),
(103,'MCQ','How can you change "Hansen" into "Nilsen" in the "LastName" column in the Persons table','UPDATE Persons SET LastName="Nilsen" WHERE LastName="Hansen"',103),
(104,'MCQ','With SQL how can you delete the records where the "FirstName" is "Peter" in the Persons Table','DELETE FROM Persons WHERE FirstName = "Peter"',103),
(105,'MCQ','With SQL how can you return the number of records in the "Persons" table','SELECT COUNT(*) FROM Persons',103),
(106,'MCQ','What is the most common type of join','INNER JOIN',103),
(107,'MCQ','Which operator is used to select values within a range','BETWEEN',103),
(108,'TF','The NOT NULL constraint enforces a column to not accept NULL values','True',103),
(109,'MCQ','Which operator is used to search for a specified pattern in a column','LIKE',103),
(110,'MCQ','Which SQL statement is used to create a database table called "Customers"','CREATE TABLE Customers',103),
(121,'MCQ','Which AWS service reduces network latency?','Amazon CloudFront',105),
(122,'MCQ','What kind of database is AWS DynamoDB?','NoSQL database',105),
(123,'MCQ','What is AWS EC2?','AWS EC2 is a virtual server in the AWS Cloud',105),
(124,'TF','AWS Regions is part of the AWS Global Infrastructure.','True',105),
(125,'MCQ','Which Amazon S3 storage class has the lowest cost?',' S3 Glacier Deep Archive ',105),
(126,'MCQ','What is AWS EFS?','AWS Elastic File System',105),
(127,'MCQ','What are Edge Locations?','Data centers that deliver data fast to the users',105),
(128,'TF','Denial-of-Service (DoS) attack comes from different sources.','False',105),
(129,'MCQ','What is the purpose of AWS Organizations service?','AWS Organizations helps you manage multiple AWS Accounts',105),
(130,'MCQ','Which of the following is AWS Migration Strategy?','Replatforming',105),
(131,'MCQ','Which perspective of the AWS Cloud Adoption Framework focuses on minimizing the business risks?','Governance Perspective',105),
(132,'MCQ','Which pillar of the AWS Well-Architected Framework focuses on recovering from service or infrastructure disruptions?','Reliability',105),
(133,'TF','Economies of scale continually reduce AWS Cloud pricing.','True',105),
(134,'MCQ','Which service sends and receives messages between application components?','AWS Simple Queue Service (AWS SQS)',105),
(135,'MCQ','Who is responsible for managing storage and database in AWS Cloud?','AWS',105),
(136,'TF','AWS Artifact is a service that provides access to AWS security and compliance reports.','True',105),
(137,'MCQ','Which AWS service helps you create users and provide them security access?','AWS Identity and Access Management (IAM)',105),
(138,'MCQ','Which AWS service helps you build text chatbots?','Amazon Lex',105),
(139,'MCQ','Can all accounts of an AWS Organization be billed with a single bill?','Yes',105),
(140,'MCQ','Which database is ideal for large organizations and enterprises?','Amazon Aurora',105),
(141,'MCQ','If an instance store reboots does the data in the instance persist?','Yes',105),
(142,'MCQ','Which sentence best describes AWS CloudWatch?','CloudWatch is a monitoring service that monitors your resources and configures automatic alarms.',105),
(143,'MCQ','What does AWS Shield protect from?','Dos and DDoS attacks',105),
(144,'TF','Based on application"s network requests AWS Web Application Firewall can block network traffic.','True',105),
(145,'TF','DNS stands for "Data Name System".','False',105),
(146,'TF','Containers are an essential concept in microservice architectures.','True',105),
(147,'TF','With AWS EC2 you only pay for the compute time that you use.','True',105),
(148,'TF','AWS Elastic Beanstalk is a service that manages web infrastructure.','True',105),
(151,'MCQ','Which of these best describes an array?','Container of objects of similar types',106),
(152,'MCQ','How do you initialize an array in C?','int arr[3] = (1 2 3};',106),
(153,'MCQ','When does the ArrayIndexOutOfBoundsException occur?','Run-time',106),
(154,'MCQ','Which of the following concepts make extensive use of arrays?','Spatial locality',106),
(155,'MCQ','What are the advantages of arrays?','Easier to store elements of same data type',106),
(156,'MCQ','In general the index of the first element in an array is __________','0',106),
(157,'MCQ','Elements in an array are accessed _____________','randomly',106),
(158,'MCQ','Process of inserting an element in stack is called ____________','Push',106),
(159,'MCQ','Process of removing an element from stack is called __________','Pop',106),
(160,'MCQ','In a stack if a user tries to remove an element from an empty stack it is called _________','Underflow',106),
(161,'MCQ','Pushing an element into stack already having five elements and stack size of 5 then stack becomes ___________','Overflow',106),
(162,'MCQ','Entries in a stack are “ordered”. What is the meaning of this statement?','There is a Sequential entry that is one by one',106),
(163,'MCQ','Which of the following is not the application of stack?','Data Transfer between two asynchronous process',106),
(164,'MCQ','Consider the usual algorithm for determining whether a sequence of parentheses is balanced. The maximum number of parentheses that appear on the stack AT ANY ONE TIME when the algorithm analyzes: (()(())(()))?','3',106),
(165,'MCQ','The postfix form of the expression (A+ B)*(C*D- E)*F / G is?','AB + CD* E – *F *G /',106),
(166,'MCQ','The data structure required to check whether an expression contains a balanced parenthesis is?','Stack',106),
(167,'MCQ','The data structure required for Breadth First Traversal on a graph is?','Queue',106),
(168,'MCQ','A queue follows __________','FIFO',106),
(169,'MCQ',' If the elements “A” “B” “C” and “D” are placed in a queue and are deleted one at a time in what order will they be removed?','ABCD',106),
(170,'MCQ',' A data structure in which elements can be inserted or deleted at/from both ends but not in the middle is?','Dequeue',106),
(171,'TF','T/F: A queue cannot be implemented using in an array.','F',106),
(172,'TF','T/F: Every node in a linked list has two components: one to store the relevant information and one to store the address.','T',106),
(173,'TF','T/F: The address of the first node in a linked list is stored in a separate location/pointer called the head.','T',106),
(174,'TF','T/F: Each node of a singly linked list has at least four components.','F',106),
(175,'TF','T/F: The algorithms to implement the operations search insert and remove are the same for sorted and unsorted list.','F',106),
(176,'TF','T/F: The link component of each node is a pointer.','T',106),
(177,'TF','T/F: Operations such as search insert and delete require a linked list to be sorted.','F',106),
(178,'TF','T/F: Building a linked list forward places the new item to be added at the beginning of the linked list.','F',106),
(179,'TF','T/F: Building a linked list backwards places the new item to be added at the end of the linked list.','F',106),
(180,'TF','T/F: In general there are three types of linked lists and they are: sorted unsorted and mixed.','F',106)
