insert into QuesOption
values
(1,'Pressing an arrow key'),
(1,'Pressing the Tab key'),
(1,'Pressing the Esc key'),
(1,'Clicking on the formula bar'),
(2,'Pressing Ctrl + C'),
(2,'Selecting Edit>Cut from the menu'),
(2,'Clicking the Cut button on the standard'),
(2,'Pressing Ctrl+X'),
(3,'Pressing enter'),
(3,'Pressing any arrow key on the keyboard'),
(3,'Clicking the Enter button on the Formula bar'),
(3,'Pressing spacebar'),
(4,'Pressing the Tab key'),
(4,'Clicking the cell'),
(4,'Pressing an arrow key'),
(4,'All of the above'),
(5,'Replace cell references'),
(5,'Return ASCII values of characters'),
(5,'Concatenate and manipulate text'),
(5,'Show formula error value'),
(6,'Right-click the row heading where you want to insert the new row and select Insert from the shortcut menu'),
(6,'Select the row heading where you want to insert the new row and select Edit >Row from the menu'),
(6,'Select the row heading where you want to insert the new row and click the Insert Row button on the standard toolbar'),
(6,'All of the above'),
(7,'Save workbook'),
(7,'Modifiy the worksheet'),
(7,'Enter text and data'),
(7,'Copy the worksheet'),
(8,'Select Edit > Select > Column from the menu'),
(8,'Click the column heading letter'),
(8,'Hold down the shift key as you click anywhere in the column'),
(8,'Hold down the Ctrl key as you click anywhere in the column'),
(9,'Select File>Properties form the menu and type 3 in the Copies to print text box'),
(9,'Select File >Print from the menu and type 3 in the Number of copies text box'),
(9,'Click the Print button on the standard toolbar to print the document then take it to Kinko’s and have 2 more copies made'),
(9,'Press Ctrl+P+3'),
(10,'Select the cell you want to place the formula into'),
(10,'Type the equals sign (=), to tell Excel that you’re about to enter a formula'),
(10,'Enter the formula using any input values and the appropriate mathematical operators that make up your formula'),
(10,'Choose the new command from the file menu'),
(11,'Select the cells containing the title text plus the range over which the title text is to be centered'),
(11,'Widen the columns'),
(11,'Select the cells containing the title text plus the range over which the title text is to be enfettered'),
(11,'Format the cells with the comma style'),
(12,'Select the column heading you want to delete and select the Delete Row button on the standard toolbar'),
(12,'Select the column heading you want to delete and select Insert Delete from the menu'),
(12,'Select the row heading you want to delete and select Edit>Delete from the menu'),
(12,'Right click the column heading you want to delet and select delete from the shortcut menu'),
(14,'Select Tools > Finder from the menu'),
(14,'Click the Find button on the standard toolbar'),
(14,'Select Insert > Find from the menu'),
(14,'Select Data > Form from the menu to open the Data Form dialog box and click the Criteria button'),
(14,'Server'),
(14,'Destination'),
(14,'Client'),
(14,'Both b and c'),
(15,'Shorten the label'),
(15,'Increase the column width'),
(15,'Decrease the column width'),
(15,'Adjust the row height'),
(16,'Shows the location of the previously active cell'),
(16,'Appears to the left of the formula bar'),
(16,'Appears below the status bar'),
(16,'Appears below the menu bar'),
(17,'Smart tip'),
(17,'Cell tip'),
(17,'Web tip'),
(17,'Soft tip'),
(18,'Solver'),
(18,'Goal seek'),
(18,'Scenario Manager'),
(18,'All of above'),
(19,'Split a worksheet into two panes'),
(19,'View different rows and columns edit the contents of a cell'),
(19,'Edit the contents of a cell'),
(19,'view different worksheets'),
(20,'standard formulas'),
(20,'array formula'),
(20,'complex formulas'),
(20,'smart formula'),
(21,'True'),
(21,'False'),
(22,'True'),
(22,'False'),
(23,'True'),
(23,'False'),
(24,'True'),
(24,'False'),
(25,'True'),
(25,'False'),
(26,'True'),
(26,'False'),
(27,'True'),
(27,'False'),
(28,'True'),
(28,'False'),
(29,'True'),
(29,'False'),
(30,'True'),
(30,'False'),
(31,'Fact table'),
(31,'Query table'),
(31,'Dimension table'),
(31,'Power BI table'),
(32,'Publish them to the Power BI service'),
(32,'Create a PDF of the report and share the PDF with others'),
(32,'Copy the .PBIX file to a file folder and give coworkers access to that folder'),
(32,'None'),
(33,'+'),
(33,'-'),
(33,'/'),
(33,'*'),
(34,'MAX'),
(34,'COUNT'),
(34,'COUNTROWS'),
(34,'None'),
(35,'Query'),
(35,'DAX'),
(35,'Model'),
(35,'None'),
(36,'OR'),
(36,'IF'),
(36,'SUMX'),
(36,'NOT'),
(37,'IF'),
(37,'DATE'),
(37,'CONCATENATE'),
(37,'COUNT'),
(38,'Power BI'),
(38,'Power BI Service'),
(38,'Query Editor'),
(38,'Visual Market Place'),
(39,'Report view'),
(39,'Query editor'),
(39,'Power BI service'),
(39,'Gateway'),
(40,'Filter'),
(40,'Function'),
(40,'Calculated column'),
(40,'Measures'),
(41,'One to Many'),
(41,'Many to Many'),
(41,'Many to One'),
(41,'One to One'),
(42,'Data Collection'),
(42,'Introduction to DAX'),
(42,'Data Preparation'),
(42,'Overview'),
(43,'ISNUMBER'),
(43,'AVERAGE'),
(43,'AND'),
(43,'CONCATENATE'),
(44,'Calculated Row'),
(44,'Measure'),
(44,'Counting'),
(44,'Calculated Colum'),
(45,'Fact table'),
(45,'Query table'),
(45,'Dimension table'),
(45,'Power BI table'),
(46,'star apple'),
(46,'banapple'),
(46,'peach apple'),
(46,'All of mentioned above'),
(47,'Files- Content Packs- Connectors'),
(47,'Databases- SQL- Azure'),
(47,'Files- SQL- Azure'),
(47,'Content Packs- Connectors- SQL'),
(48,'IF'),
(48,'VLOOKUP'),
(48,'SUM'),
(48,'COUNT'),
(49,'Visualizations- datasets- reports- dashboards- tiles'),
(49,'Visual Studio- C#- and JSON files'),
(49,'Tiles- dashboards- databases- mobile device'),
(49,'None of the above'),
(50,'Dashboards'),
(50,'Reports'),
(50,'Datasets'),
(50,'All of the above'),
(51,'True'),
(51,'False'),
(52,'True'),
(52,'False'),
(53,'True'),
(53,'False'),
(54,'True'),
(54,'False'),
(55,'True'),
(55,'False'),
(56,'True'),
(56,'False'),
(57,'True'),
(57,'False'),
(58,'True'),
(58,'False'),
(59,'True'),
(59,'False'),
(60,'True'),
(60,'False'),
(61,'System.out.println("Hello World");'),
(61,'print ("Hello World");'),
(61,'Console.WriteLine("Hello World");    '),
(61,'cout << "Hello World";'),
(62,'False  '),
(62,'True'),
(63,'// This is a comment'),
(63,'/* This is a comment'),
(63,'# This is a comment'),
(64,'Txt'),
(64,'myString'),
(64,'string'),
(64,'str'),
(65,'double x = 5;'),
(65,'x = 5;'),
(65,'num x = 5'),
(65,'int x = 5;'),
(66,'int x = 2.8D;'),
(66,'int x = 2.8;'),
(66,'byte x = 2.8'),
(66,'double x = 2.8D;'),
(67,'length'),
(67,'length()'),
(67,'getLength()'),
(68,'The * sign'),
(68,'The & sign'),
(68,'The + sign '),
(69,'True'),
(69,'False'),
(70,'False'),
(70,'True '),
(71,'='),
(71,'<>'),
(71,'==  '),
(71,'><'),
(72,'()'),
(72,'[]'),
(72,'{}'),
(73,'1  '),
(73,'0 '),
(74,'MyMethod.'),
(74,'MyMethod()'),
(74,'(MyMethod)'),
(74,'myMethod[]'),
(75,'(MyMethod);'),
(75,'MyMethod;'),
(75,'myMethod[];'),
(75,'MyMethod();'),
(76,'class'),
(76,'class()'),
(76,'MyClass'),
(76,'className'),
(77,'MyClass myObj = new MyClass();'),
(77,'class myObj = new MyClass();'),
(77,'new myObj = MyClass();'),
(77,'class MyClass = new myObj();'),
(78,'True'),
(78,'False'),
(79,'special'),
(79,'enum'),
(79,'const'),
(79,'void'),
(80,'#'),
(80,'x'),
(80,'*'),
(80,'%'),
(81,'public'),
(81,'abstract'),
(81,'final'),
(81,'private'),
(82,'if x > y then:'),
(82,'if (x > y)  '),
(82,'if x > y:'),
(83,'while x > y:'),
(83,'while (x > y)'),
(83,'x > y while {'),
(83,'while x > y {'),
(84,'get84break'),
(84,'void'),
(84,'return'),
(85,'return '),
(85,'break'),
(85,'exit'),
(85,'stop'),
(86,'Structured Query Language'),
(86,'Structured Question Language'),
(86,'Strong Question Language'),
(87,'SELECT'),
(87,'EXTRACT'),
(87,'GET'),
(87,'OPEN'),
(88,'SAVE AS '),
(88,'UPDATE'),
(88,'SAVE'),
(88,'MODIFY'),
(89,'REMOVE'),
(89,'COLLAPSE'),
(89,'DELETE'),
(90,'INSERT NEW'),
(90,'ADD RECORD'),
(90,'INSERT INTO'),
(90,'ADD NEW'),
(91,'SELECT Persons.FirstName'),
(91,'EXTRACT FirstName FROM Persons'),
(91,'SELECT FirstName FROM Persons'),
(92,'SELECT Persons'),
(92,'SELECT * FROM Persons'),
(92,'SELECT [all] FROM Persons'),
(92,'SELECT *.Persons'),
(93,'SELECT [all] FROM Persons WHERE FirstName="Peter"'),
(93,'SELECT * FROM Persons WHERE FirstName="Peter"'),
(93,'SELECT [all] FROM Persons WHERE FirstName LIKE "Peter"'),
(93,'SELECT * FROM Persons WHERE FirstName<>"Peter"'),
(94,'SELECT * FROM Persons WHERE FirstName LIKE "%a"'),
(94,'SELECT * FROM Persons WHERE FirstName="a"'),
(94,'SELECT * FROM Persons WHERE FirstName="%a%"'),
(94,'SELECT * FROM Persons WHERE FirstName LIKE "a%"'),
(95,'False'),
(95,'True'),
(96,'SELECT * FROM Persons WHERE FirstName<>"Peter" AND LastName<>"Jackson"'),
(96,'SELECT FirstName="Peter" LastName="Jackson" FROM Persons'),
(96,'SELECT * FROM Persons WHERE FirstName="Peter" AND LastName="Jackson"'),
(97,'SELECT LastName>"Hansen" AND LastName<"Pettersen" FROM Persons '),
(97,'SELECT * FROM Persons WHERE LastName BETWEEN "Hansen" AND "Pettersen"'),
(97,'SELECT * FROM Persons WHERE LastName>"Hansen" AND LastName<"Pettersen"'),
(98,'SELECT DIFFERENT'),
(98,'SELECT UNIQUE'),
(98,'SELECT DISTINCT '),
(99,'SORT '),
(99,'ORDER BY '),
(99,'SORT BY'),
(99,'ORDER'),
(100,'SELECT * FROM Persons ORDER FirstName DESC'),
(100,'SELECT * FROM Persons SORT BY "FirstName" DESC'),
(100,'SELECT * FROM Persons ORDER BY FirstName DESC'),
(100,'SELECT * FROM Persons SORT "FirstName" DESC'),
(101,'INSERT INTO Persons VALUES ("Jimmy" "Jackson"'),
(101,'INSERT VALUES ("Jimmy" "Jackson") INTO Persons'),
(101,'INSERT ("Jimmy" "Jackson") INTO Persons'),
(102,'INSERT INTO Persons (LastName) VALUES ("Olsen")'),
(102,'INSERT INTO Persons ("Olsen") INTO LastName'),
(102,'INSERT ("Olsen") INTO Persons (LastName)'),
(103,'MODIFY Persons SET LastName="Nilsen" WHERE LastName="Hansen’'),
(103,'UPDATE Persons SET LastName="Hansen" INTO LastName="Nilsen"'),
(103,'MODIFY Persons SET LastName="Hansen" INTO LastName="Nilsen'),
(103,'UPDATE Persons SET LastName="Nilsen" WHERE LastName="Hansen"'),
(104,'DELETE FirstName="Peter" FROM Persons'),
(104,'DELETE FROM Persons WHERE FirstName = "Peter"'),
(104,'DELETE ROW FirstName="Peter" FROM Persons'),
(105,'SELECT COLUMNS(*) FROM Persons'),
(105,'SELECT LEN(*) FROM Persons'),
(105,'SELECT COUNT(*) FROM Persons'),
(105,'SELECT NO(*) FROM Persons'),
(106,'JOINED TABLE'),
(106,'INSIDE JOIN'),
(106,'INNER JOIN'),
(106,'JOINED'),
(107,'WITHIN '),
(107,'BETWEEN'),
(107,'RANGE'),
(108,'False'),
(108,'True'),
(109,'FROM'),
(109,'LIKE'),
(109,'GET'),
(110,'CREATE TABLE Customers'),
(110,'CREATE DATABASE TAB Customers'),
(110,'CREATE DB Customers'),
(110,'CREATE DATABASE TABLE Customers'),
(121,'Amazon CloudFront'),
(121,'AWS Direct Connect'),
(121,'Elastic Load Balancing'),
(121,'AWS Transit Gateway'),
(122,'NoSQL database'),
(122,'Document database'),
(122,'Relational database'),
(123,'AWS EC2 is a resource monitoring service'),
(123,'AWS EC2 is a virtual server in the AWS Cloud'),
(123,'AWS EC2 is a serverless compute service'),
(123,'AWS EC2 is a data center'),
(124,'True'),
(124,'False'),
(125,'S3 Standard'),
(125,'S3 Intelligent-Tiering'),
(125,'S3 Glacier Deep Archive'),
(126,'AWS Enterprise File System'),
(126,'AWS Efficient File System'),
(126,'AWS Elastic File System'),
(127,'Data centers that store petabytes of data'),
(127,'Physical hard drives'),
(127,'Data centers that deliver data fast to the users'),
(127,'AWS Regions'),
(128,'True'),
(128,'False'),
(129,'AWS Organizations helps you manage multiple AWS Accounts'),
(129,'AWS Organizations groups your applications and manages them'),
(129,'AWS Organizations organizes your services and makes service usage reports'),
(129,'AWS Organizations optimizes your system performance'),
(130,'Governance'),
(130,'Replatforming'),
(130,'Auditability'),
(131,'Governance Perspective'),
(131,'Operations Perspective'),
(131,'People Perspective'),
(131,'Business Perspective'),
(132,'Reliability'),
(132,'Performance efficiency'),
(132,'Operational excellence'),
(133,'True'),
(133,'False'),
(134,'AWS CloudTrail'),
(134,'AWS Snowmobile'),
(134,'AWS Simple Queue Service (AWS SQS)'),
(134,'AWS Lambda'),
(135,'Customers'),
(135,'AWS'),
(136,'False'),
(136,'True'),
(137,'AWS Direct Connect'),
(137,'AWS CloudFormation'),
(137,'AWS Identity and Access Management (IAM)'),
(137,'AWS Redshift'),
(138,'Amazon Polly'),
(138,'Amazon Transcribe'),
(138,'Amazon Lex'),
(138,'Amazon Comprehend'),
(139,'Yes'),
(139,'No'),
(140,'PostgreSQL'),
(140,'Amazon Aurora'),
(140,'MySQL'),
(141,'No'),
(141,'Yes'),
(142,'CloudWatch monitors your account and recommends you cost optimization and performance improvement actions.'),
(142,'CloudWatch is a service that logs your AWS environment Actions. It is used to create events that describe how your application is being used.'),
(142,'CloudWatch is a monitoring service that monitors your resources and configures automatic alarms.'),
(143,'Software vulnerabilities'),
(143,'Infrastructure threats'),
(143,'Dos and DDoS attacks'),
(144,'False'),
(144,'True'),
(145,'False'),
(145,'True'),
(146,'True'),
(146,'False'),
(147,'True'),
(147,'False'),
(148,'True'),
(148,'False'),
(151,'A data structure that shows a hierarchical behavior'),
(151,'Container of objects of similar types'),
(151,'Arrays are immutable once initialised'),
(151,'Array is not a data structure'),
(152,'int arr[3] = (1,2,3);'),
(152,'int arr[3] = (1 2 3);'),
(152,'int arr[3] = (1 2 3};'),
(152,'int arr[3] = (1;2;3);'),
(153,'Compile-time'),
(153,'Run-time'),
(153,'Not an error'),
(153,'Not an exception at all'),
(154,'Binary trees'),
(154,'Scheduling of processes'),
(154,'Caching'),
(154,'Spatial locality'),
(155,'Objects of mixed data types can be stored'),
(155,'Elements in an array cannot be sorted'),
(155,'Index of first element of an array is 1'),
(155,'Easier to store elements of same data type'),
(156,'0'),
(156,'-1'),
(156,'2'),
(156,'1'),
(157,'randomly'),
(157,'sequentially'),
(157,'exponentially'),
(157,'logarithmically'),
(158,'Create'),
(158,'Push'),
(158,'Evaluation'),
(158,'Pop'),
(159,'Create'),
(159,'Push'),
(159,'Evaluation'),
(159,'Pop'),
(160,'Underflow'),
(160,'Empty collection'),
(160,'Overflow'),
(160,'Garbage Collection'),
(161,'Overflow'),
(161,'Crash'),
(161,'Underflow'),
(161,'User flow'),
(162,'A collection of stacks is sortable'),
(162,'Stack entries may be compared with the ‘<‘ operation'),
(162,'The entries are stored in a linked list'),
(162,'There is a Sequential entry that is one by one'),
(163,'A parentheses balancing program'),
(163,'Tracking of local variables at run time'),
(163,'Compiler Syntax Analyzer'),
(163,'Data Transfer between two asynchronous process'),
(164,'1'),
(164,'2'),
(164,'3'),
(164,'4 or more'),
(165,'AB+ CD*E – FG /**'),
(165,'AB + CD* E – F **G /'),
(165,'AB + CD* E – *F *G /'),
(165,'AB + CDE * – * F *G /'),
(166,'Stack'),
(166,'Queue'),
(166,'Array'),
(166,'Tree'),
(167,'Stack'),
(167,'Array'),
(167,'Queue'),
(167,'Tree'),
(168,'FIFO (First In First Out) principle'),
(168,'LIFO (Last In First Out) principle'),
(168,'Ordered array'),
(168,'Linear tree'),
(169,'ABCD'),
(169,'DCBA'),
(169,'DCAB'),
(169,'ABDC'),
(170,'Queue'),
(170,'Circular queue'),
(170,'Dequeue'),
(170,'Priority queue'),
(171,'True'),
(171,'False'),
(172,'True'),
(172,'False'),
(173,'True'),
(173,'False'),
(174,'True'),
(174,'False'),
(175,'True'),
(175,'False'),
(176,'True'),
(176,'False'),
(177,'True'),
(177,'False'),
(178,'True'),
(178,'False'),
(179,'True'),
(179,'False'),
(180,'True'),
(180,'False')
